server:
  port : 8080
spring:
  data:
     mongodb:
       host: localhost
       port: 27017
       username: user
       password: "123456"
       database: test
  jpa:
    show-sql: true
logging:
  level:
    root: debug
  org:
    springframework:
      data:
        mongodb:
          core: DEBUG

